services:
  postgres:
    image: postgres:16.1-alpine3.19
    hostname: postgres.pfc
    container_name: postgres.pfc
    restart: always
    env_file:
      - .env
    environment:
      - POSTGRES_USER=${POSTGRES_USER}
      - POSTGRES_PASSWORD=${POSTGRES_PASSWORD}
    volumes:
      - .volumes/postgres:/var/lib/postgresql/data
    ports:
      - '5432:5432'
